name: Cargo

on:
  push:
    branches:
    - main
    - release/*
  pull_request:
    branches:
    - main
    - release/*

permissions: read-all

jobs:
  cargo:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    name: Cargo
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@74b568e8591fbb3115c70f3436a0c6b0909a8504
      with:
        egress-policy: audit
    - name: Checkout repository
      uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
    - name: Prepare Machine
      run: scripts/prepare-machine.ps1 -Tls openssl -ForBuild
      shell: pwsh
    - name: Install Perl
      if: runner.os == 'Windows'
      uses: shogo82148/actions-setup-perl@8eab529e8d2b76c858ac03481651d5e5cf738366
      with:
        perl-version: '5.34'
    - name: Install NASM
      if: runner.os == 'Windows'
      uses: ilammy/setup-nasm@10788e307d96af7013172d66126322c70b22efb9
    - name: Install Cargo
      if: runner.os == 'Linux'
      run: curl https://sh.rustup.rs -sSf | sh -s -- -y
    - name: Cargo build
      run: cargo build --all
    - name: Cargo test
      run: cargo test --all
    - name: Cargo Publish (dry run)
      run: cargo publish --dry-run
